// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSettingsByBotID = `-- name: DeleteSettingsByBotID :exec
UPDATE bots
SET max_context_load_time = 1440,
    language = 'auto',
    allow_guest = false,
    group_require_mention = true,
    chat_model_id = NULL,
    memory_model_id = NULL,
    embedding_model_id = NULL,
    vlm_model_id = NULL,
    background_model_id = NULL,
    image_model_id = NULL,
    search_provider_id = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) DeleteSettingsByBotID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSettingsByBotID, id)
	return err
}

const getSettingsByBotID = `-- name: GetSettingsByBotID :one
SELECT
  bots.id AS bot_id,
  bots.max_context_load_time,
  bots.language,
  bots.allow_guest,
  bots.group_require_mention,
  chat_models.model_id AS chat_model_id,
  memory_models.model_id AS memory_model_id,
  embedding_models.model_id AS embedding_model_id,
  vlm_models.model_id AS vlm_model_id,
  background_models.model_id AS background_model_id,
  image_models.model_id AS image_model_id,
  search_providers.id AS search_provider_id
FROM bots
LEFT JOIN models AS chat_models ON chat_models.id = bots.chat_model_id
LEFT JOIN models AS memory_models ON memory_models.id = bots.memory_model_id
LEFT JOIN models AS embedding_models ON embedding_models.id = bots.embedding_model_id
LEFT JOIN models AS vlm_models ON vlm_models.id = bots.vlm_model_id
LEFT JOIN models AS background_models ON background_models.id = bots.background_model_id
LEFT JOIN models AS image_models ON image_models.id = bots.image_model_id
LEFT JOIN search_providers ON search_providers.id = bots.search_provider_id
WHERE bots.id = $1
`

type GetSettingsByBotIDRow struct {
	BotID               pgtype.UUID `json:"bot_id"`
	MaxContextLoadTime  int32       `json:"max_context_load_time"`
	Language            string      `json:"language"`
	AllowGuest          bool        `json:"allow_guest"`
	GroupRequireMention bool        `json:"group_require_mention"`
	ChatModelID         pgtype.Text `json:"chat_model_id"`
	MemoryModelID       pgtype.Text `json:"memory_model_id"`
	EmbeddingModelID    pgtype.Text `json:"embedding_model_id"`
	VlmModelID          pgtype.Text `json:"vlm_model_id"`
	BackgroundModelID   pgtype.Text `json:"background_model_id"`
	ImageModelID        pgtype.Text `json:"image_model_id"`
	SearchProviderID    pgtype.UUID `json:"search_provider_id"`
}

func (q *Queries) GetSettingsByBotID(ctx context.Context, id pgtype.UUID) (GetSettingsByBotIDRow, error) {
	row := q.db.QueryRow(ctx, getSettingsByBotID, id)
	var i GetSettingsByBotIDRow
	err := row.Scan(
		&i.BotID,
		&i.MaxContextLoadTime,
		&i.Language,
		&i.AllowGuest,
		&i.GroupRequireMention,
		&i.ChatModelID,
		&i.MemoryModelID,
		&i.EmbeddingModelID,
		&i.VlmModelID,
		&i.BackgroundModelID,
		&i.ImageModelID,
		&i.SearchProviderID,
	)
	return i, err
}

const upsertBotSettings = `-- name: UpsertBotSettings :one
WITH params AS (
  SELECT
    $1::uuid as bot_id,
    $2::int as max_context_load_time,
    $3::text as language,
    $4::bool as allow_guest,
    $5::bool as group_require_mention,
    $6::uuid as chat_model_id,
    $7::uuid as memory_model_id,
    $8::uuid as embedding_model_id,
    $9::uuid as vlm_model_id,
    $10::uuid as background_model_id,
    $11::uuid as image_model_id,
    $12::uuid as search_provider_id
),
updated AS (
  UPDATE bots
  SET max_context_load_time = params.max_context_load_time,
      language = params.language,
      allow_guest = params.allow_guest,
      group_require_mention = params.group_require_mention,
      chat_model_id = COALESCE(params.chat_model_id, bots.chat_model_id),
      memory_model_id = COALESCE(params.memory_model_id, bots.memory_model_id),
      embedding_model_id = COALESCE(params.embedding_model_id, bots.embedding_model_id),
      vlm_model_id = CASE
          WHEN params.vlm_model_id IS NULL THEN bots.vlm_model_id
          WHEN params.vlm_model_id = '00000000-0000-0000-0000-000000000000'::uuid THEN NULL
          ELSE params.vlm_model_id
      END,
      background_model_id = CASE
          WHEN params.background_model_id IS NULL THEN bots.background_model_id
          WHEN params.background_model_id = '00000000-0000-0000-0000-000000000000'::uuid THEN NULL
          ELSE params.background_model_id
      END,
      image_model_id = CASE
          WHEN params.image_model_id IS NULL THEN bots.image_model_id
          WHEN params.image_model_id = '00000000-0000-0000-0000-000000000000'::uuid THEN NULL
          ELSE params.image_model_id
      END,
      search_provider_id = COALESCE(params.search_provider_id, bots.search_provider_id),
      updated_at = now()
  FROM params
  WHERE bots.id = params.bot_id
  RETURNING bots.id, bots.max_context_load_time, bots.language, bots.allow_guest, bots.group_require_mention, bots.chat_model_id, bots.memory_model_id, bots.embedding_model_id, bots.vlm_model_id, bots.background_model_id, bots.image_model_id, bots.search_provider_id
)
SELECT
  updated.id AS bot_id,
  updated.max_context_load_time,
  updated.language,
  updated.allow_guest,
  updated.group_require_mention,
  chat_models.model_id AS chat_model_id,
  memory_models.model_id AS memory_model_id,
  embedding_models.model_id AS embedding_model_id,
  vlm_models.model_id AS vlm_model_id,
  background_models.model_id AS background_model_id,
  image_models.model_id AS image_model_id,
  search_providers.id AS search_provider_id
FROM updated
LEFT JOIN models AS chat_models ON chat_models.id = updated.chat_model_id
LEFT JOIN models AS memory_models ON memory_models.id = updated.memory_model_id
LEFT JOIN models AS embedding_models ON embedding_models.id = updated.embedding_model_id
LEFT JOIN models AS vlm_models ON vlm_models.id = updated.vlm_model_id
LEFT JOIN models AS background_models ON background_models.id = updated.background_model_id
LEFT JOIN models AS image_models ON image_models.id = updated.image_model_id
LEFT JOIN search_providers ON search_providers.id = updated.search_provider_id
`

type UpsertBotSettingsParams struct {
	MaxContextLoadTime  int32       `json:"max_context_load_time"`
	Language            string      `json:"language"`
	AllowGuest          bool        `json:"allow_guest"`
	GroupRequireMention bool        `json:"group_require_mention"`
	ChatModelID         pgtype.UUID `json:"chat_model_id"`
	MemoryModelID       pgtype.UUID `json:"memory_model_id"`
	EmbeddingModelID    pgtype.UUID `json:"embedding_model_id"`
	VlmModelID          pgtype.UUID `json:"vlm_model_id"`
	BackgroundModelID   pgtype.UUID `json:"background_model_id"`
	ImageModelID        pgtype.UUID `json:"image_model_id"`
	SearchProviderID    pgtype.UUID `json:"search_provider_id"`
	ID                  pgtype.UUID `json:"id"`
}

type UpsertBotSettingsRow struct {
	BotID               pgtype.UUID `json:"bot_id"`
	MaxContextLoadTime  int32       `json:"max_context_load_time"`
	Language            string      `json:"language"`
	AllowGuest          bool        `json:"allow_guest"`
	GroupRequireMention bool        `json:"group_require_mention"`
	ChatModelID         pgtype.Text `json:"chat_model_id"`
	MemoryModelID       pgtype.Text `json:"memory_model_id"`
	EmbeddingModelID    pgtype.Text `json:"embedding_model_id"`
	VlmModelID          pgtype.Text `json:"vlm_model_id"`
	BackgroundModelID   pgtype.Text `json:"background_model_id"`
	ImageModelID        pgtype.Text `json:"image_model_id"`
	SearchProviderID    pgtype.UUID `json:"search_provider_id"`
}

func (q *Queries) UpsertBotSettings(ctx context.Context, arg UpsertBotSettingsParams) (UpsertBotSettingsRow, error) {
	row := q.db.QueryRow(ctx, upsertBotSettings,
		arg.ID,
		arg.MaxContextLoadTime,
		arg.Language,
		arg.AllowGuest,
		arg.GroupRequireMention,
		arg.ChatModelID,
		arg.MemoryModelID,
		arg.EmbeddingModelID,
		arg.VlmModelID,
		arg.BackgroundModelID,
		arg.ImageModelID,
		arg.SearchProviderID,
	)
	var i UpsertBotSettingsRow
	err := row.Scan(
		&i.BotID,
		&i.MaxContextLoadTime,
		&i.Language,
		&i.AllowGuest,
		&i.GroupRequireMention,
		&i.ChatModelID,
		&i.MemoryModelID,
		&i.EmbeddingModelID,
		&i.VlmModelID,
		&i.BackgroundModelID,
		&i.ImageModelID,
		&i.SearchProviderID,
	)
	return i, err
}
